### PR TITLE
fix(mcp): preserve tool input schema types and required fields

### LINKED ISSUE #5109: OpenAI Agent Node Strict Tool Calling Mode fails on json schema validation with Custom MCP Tool
### Describe the bug

I get the following error (I believe from OpenAI's API) when trying to run an agent node that has a Custom MCP tool attached.

```
Error in Agent node: 400 Invalid schema for function 'get_table_schema': In context=('properties', 'tableName'), schema must have a 'type' key.
```

This is the json schema for my tool function:
```json
{
  "type": "object",
  "properties": {
  	"tableName": {
  		"type": "string",
  		"description": "Name of the table or view to get schema details for"
  	}
  },
  "required": ["tableName"]
}
```

I tried many variations of the JSON schema to rule out actual problems there, so I believe the issue does not lie with the schema itself.

I dug into the codebase with the help of Claude and this is eventually what I got to, basically that the issue may lie in the json schema -> zod -> json schema (for OpenAI API) pipeline. This could be wrong, but it was the best I could do without running Flowise locally and debugging there. Whatever is coming out of `packages/components/nodes/agents/OpenAIAssistant/OpenAIAssistant.ts:1159` as the `parameters` object does not have the `type` keys from my originally passed in json schema.

From Claude:
```
 Here's the complete flow of how your MCP JSON schema becomes the tool object in the OpenAI Assistant:

  Schema Conversion Pipeline

  1. MCP Server → MCP Toolkit

  - File: packages/components/nodes/tools/MCP/core.ts:90
  - Your MCP server returns tools with inputSchema (JSON Schema)
  - this._tools = await this.client.request({ method: 'tools/list' }, ListToolsResultSchema)

  2. JSON Schema → Zod Schema

  - File: packages/components/nodes/tools/MCP/core.ts:111
  - argsSchema: createSchemaModel(tool.inputSchema) converts your JSON schema
  - However, createSchemaModel() at line 159-175 loses all type information:
  const schemaProperties = Object.entries(inputSchema.properties).reduce((acc, [key, _]) => {
      acc[key] = z.any()  // <-- All properties become z.any()!
      return acc
  }, {} as Record<string, import('zod').ZodTypeAny>)

  3. Zod Schema → LangChain Tool

  - File: packages/components/nodes/tools/MCP/core.ts:135
  - tool() function from @langchain/core/tools creates a LangChain Tool object
  - This is NOT a DynamicStructuredTool, just a regular Tool

  4. Tool → OpenAI Assistant

  - File: packages/components/nodes/agents/OpenAIAssistant/OpenAIAssistant.ts:1158
  - The tool parameter is the LangChain Tool from step 3
  - zodToJsonSchema(tool.schema) converts back to JSON Schema for OpenAI
  - Since MCP tools are regular Tool objects (not DynamicStructuredTool), the strict validation logic at lines 1165 and 1194 never 
  applies

  The Problem

  You're exactly right - there's a lossy conversion:
  1. Your MCP JSON Schema (with proper types, constraints, etc.)
  2. → Zod schema with z.any() (loses all type information)
  3. → JSON Schema (basic object structure only)

  The DynamicStructuredTool.isStrict() method only applies to OpenAPI tools, not MCP tools, so your MCP tools never benefit from strict
  schema validation even when "Strict Tool Calling" is enabled.
```

### To Reproduce

1. Create an Agentflow (v2)
2. Create an Agent node - ChatOpenAI type
3. Ensure "Strict Tool Calling" property is enabled
4. Add a CustomMCP tool with a tool function that a comparable schema (an object with any simple properties)
5. Run flow, will always break with similar above error

### Expected behavior

I can't seem to use OpenAI's strict tool calling feature with my CustomMCP server tools

### Screenshots

_No response_

### Flow

_No response_

### Use Method

Docker

### Flowise Version

3.0.5

### Operating System

Linux

### Browser

Chrome

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by HenryHengZJ**
## Summary

- MCP tools were losing all type information and `required` fields because `createSchemaModel` mapped every property to `z.any()`
- Rather than reimplement a JSON-Schema-to-Zod converter (lossy for `$ref`, `allOf`, `anyOf`, enums, nested objects), pass the MCP server's `inputSchema` straight through to LangChain's `tool()` — the `JsonSchema7Type` overload has been supported since `@langchain/core` 1.1.x.
- Downstream tool serializers (`Agent`, `Tool`, `OpenAIAssistant`) to uptake these changes

### Example 1 — typed params with required fields

MCP server with the following `inputSchema` for a `create_issue` tool:

```json
{
  "type": "object",
  "properties": {
    "owner":      { "type": "string",  "description": "Repo owner" },
    "repo":       { "type": "string",  "description": "Repo name" },
    "title":      { "type": "string" },
    "project_id": { "type": "integer" },
    "draft":      { "type": "boolean" }
  },
  "required": ["owner", "repo", "title"]
}
```

**Before** — what the LLM saw after `createSchemaModel`:

```json
{
  "type": "object",
  "properties": {
    "owner":      {},
    "repo":       {},
    "title":      {},
    "project_id": {},
    "draft":      {}
  }
}
```

LLM response:

```json
{ "name": "create_issue", "arguments": {} }
```

Tool call fails — `owner`, `repo`, `title` missing. OpenAI strict mode rejects the schema outright because property `type` keys are absent.

**After** — we straightaway pass the raw `inputSchema` and preserve everything. LLM response:

```json
{
  "name": "create_issue",
  "arguments": {
    "owner": "flowiseai",
    "repo":  "Flowise",
    "title": "Fix MCP schema handling"
  }
}
```

### Example 2 — enum constraints

```json
{
  "type": "object",
  "properties": {
    "priority": { "type": "string", "enum": ["low", "medium", "high"] }
  },
  "required": ["priority"]
}
```

**Before:** `priority` was `z.any()` — LLM would pass `"urgent"`, `"P1"`, or anything else.
**After:** the enum is preserved; the model provider enforces one of `low | medium | high`.

### Example 3 — nested object

```json
{
  "type": "object",
  "properties": {
    "filter": {
      "type": "object",
      "properties": {
        "status": { "type": "string" },
        "since":  { "type": "string", "format": "date-time" }
      },
      "required": ["status"]
    }
  },
  "required": ["filter"]
}
```

**Before:** nested `filter` became `z.any()` — the LLM received no guidance on inner structure and commonly sent `"filter": "open"` as a string.
**After:** full nested schema reaches the model; inner `required` and `format` are preserved.

### Example 4 — no input schema

A tool like `get_current_time` with no params.

**Before:** `createSchemaModel` threw `Invalid schema type or missing properties`; the tool was silently dropped from the toolkit because `Promise.allSettled` swallowed the rejection.
**After:** tool registers correctly with an empty object schema.

### CODE REVIEW

File: packages/components/src/utils.ts [hunk 1]
```diff
@@ -2303,3 +2304,38 @@ export const isReasoningModelOpenAI = (name: string): boolean => {
...
+
+/**
+ * Normalizes a tool schema into a plain JSON Schema object.
+ *
+ * LangChain tools may expose their `schema` as either a Zod schema (has `_def`)
+ * or an already-plain JSON Schema (e.g. MCP tools). This helper handles both,
+ * deep-clones plain objects to prevent accidental mutation, and strips the
+ * `$schema` marker so the result is safe to embed in LLM tool definitions.
+ */
+export const toolSchemaToJsonSchema = (schema: unknown): ToolJsonSchema => {
```
Comment (jocelynlin-wd) [inline packages/components/src/utils.ts:2333]: medium-priority
> `toolSchemaToJsonSchema(null/undefined)` returns null but its return type is non-nullable. Callers in Tool.ts could get a surprise null where they spread .properties. Easy fix: add an early return of `{ type: 'object', properties: {} }` for falsy input

File: packages/components/src/utils.ts [hunk 2]
```diff
@@ -2303,3 +2304,38 @@ export const isReasoningModelOpenAI = (name: string): boolean => {
...
+
+type ZodToJsonSchemaInput = Parameters<typeof zodToJsonSchema>[0]
+
+/**
+ * Type guard detecting a Zod schema without importing Zod's types directly.
+ *
+ * Using `Parameters<typeof zodToJsonSchema>[0]` keeps the guard compatible with
+ * whichever Zod major version (`^3 || ^4`) TypeScript resolves at the call site.
+ */
+export const isZodSchema = (schema: unknown): schema is ZodToJsonSchemaInput =>
```
Comment (jocelynlin-wd) [inline packages/components/src/utils.ts:2322]: medium-priority
> `isZodSchema` false positive — a plain JSON Schema object that happens to have a `_def` key gets passed to `zodToJsonSchema`, which would throw or produce garbage. Low probability but a real edge case. Easy fix: also check for `typeof schema.parse === 'function'`.

**Review by jocelynlin-wd — APPROVED** [review]

File: packages/components/src/utils.ts (hunk 2 above)
Comment (HenryHengZJ) [reply packages/components/src/utils.ts:2322]: resolved https://github.com/FlowiseAI/Flowise/pull/6248/commits/8341c4ba64e9a4c09f3a902318565a56e5429a03

File: packages/components/src/utils.ts (hunk 1 above)
Comment (HenryHengZJ) [reply packages/components/src/utils.ts:2333]: resolved https://github.com/FlowiseAI/Flowise/pull/6248/commits/8341c4ba64e9a4c09f3a902318565a56e5429a03
