### PR TITLE
[Bugfix] Milvus search error

### LINKED ISSUE #3622: [BUG] Milvus search error
**Describe the bug**
When I use Milvus a Vector Store to retrieve the documents based on user input I get the following error:
```
Error: Error searching data: {"status":{"extra_info":{},"error_code":"UnexpectedError","reason":"fail to search on QueryNode 63: queryHook execution failed: service unavailable: search params in wrong format
character 'o' looking for beginning of value","code":2,"retriable"
,"detail":"failed to search: failed to search/query delegator 63 for channel in01-0fb909e951340bb-rootcoord-dml_7_447376391097125769v0: fail to search on QueryNode 63: queryHook execution failed: service unavailable: search params in wrong format
character 'o' looking for beginning of value"},"results":[]}
```

**Expected behavior**
I should receive the documents from the vector store.

**Setup**

-   Installation `pnpm start`
-   Flowise Version: 2.2.1
-   OS:macOS, Windows
-   Browser: chrome

### PR DESCRIPTION
**Pull request by eduardconstantin**
Fixes #3622

### CODE REVIEW

File: packages/components/nodes/vectorstores/Milvus/Milvus.ts [hunk 1]
```diff
@@ -364,7 +364,7 @@ const similaritySearchVectorWithScore = async (query: number[], k: number, vecto
         anns_field: vectorStore.vectorField,
         topk: k.toString(),
         metric_type: vectorStore.indexCreateParams.metric_type,
-        params: vectorStore.indexSearchParams.toString()
+        params: JSON.stringify(vectorStore.indexSearchParams)
```
Comment (HenryHengZJ) [inline packages/components/nodes/vectorstores/Milvus/Milvus.ts:367]: thanks @eduardconstantin !

**Review by HenryHengZJ — APPROVED** [review]
