### PR TITLE
Fix: Add keep-alive options to Redis clients to prevent idle timeouts and socket closing.

### LINKED ISSUE #2186: [BUG] Socket closed unexpectedly - Redis
I have installed the Flowiseai using the traditional method (docker) as well as Kubernetes pods using unofficial chart.
In both of those cases whenever I attempt to connect to the redis store to store vector embeddings I get the following error:

```bash
2024-04-15 07:03:35 [INFO]: Starting Flowise...
2024-04-15 07:03:35 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2024-04-15 07:03:36 [INFO]: 📦 [server]: Data Source is being initialized!
2024-04-15 07:03:38 [INFO]: 📦 [server]: Data Source has been initialized!
2024-04-15 07:24:32 [INFO]: ⬆️ POST /api/v1/vector/internal-upsert/962166d0-816d-4c8d-8a2e-341a53495b37
2024-04-15 07:25:32 [ERROR]: uncaughtException:  Socket closed unexpectedly
Error: Socket closed unexpectedly
    at Socket.<anonymous> (/usr/local/lib/node_modules/flowise/node_modules/@redis/client/dist/lib/client/socket.js:194:118)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:517:28)
    at TCP.<anonymous> (node:net:350:12)
```

Not sure if this is the issue but it seems like its Redis communication problem:
[https://stackoverflow.com/questions/71574823/reusing-redis-connection-socket-closed-unexpectedly-node-redis](url)
[https://community.fly.io/t/redis-socketclosedunexpectedlyerror-socket-closed-unexpectedly/5897](url)

image

### PR DESCRIPTION
**Pull request by nikitas-novatix**
**Problem:**

When Flowise is deployed with Redis (especially in Queue Mode or environments like Azure Cache for Redis with idle timeouts), Redis connections can be closed by the server after a period of inactivity (e.g., 10-15 minutes). This results in `uncaughtException: Socket closed unexpectedly` errors, crashing worker processes or causing failures in other Redis-dependent components.

This issue is tracked in #2186.

**Solution:**

This PR adds keep-alive mechanisms to the Redis clients used throughout Flowise to ensure connections remain active even during idle periods. The following settings were added to the respective client configurations:

-   **Core Queue Mode (@redis/client):** Added `socket: { keepAlive: 60000 }` and `pingInterval: 60000` to the clients used by `RedisEventPublisher` and `RedisEventSubscriber`.
-   **BullMQ (QueueManager - ioredis):** Added `keepAlive: 60000` and `enableReadyCheck: true` to the `ioredis` connection configuration used by BullMQ.
-   **Other `ioredis` Clients:** Added `keepAlive: 60000` and a default `retryStrategy` to clients used in `CachePool`, `RateLimiterManager`, `RedisCache`, `RedisEmbeddingsCache`, and `RedisBackedChatMemory` nodes.
-   **Other `@redis/client` Clients:** Added `socket: { keepAlive: 60000 }` and `pingInterval: 60000` to the client used in the `Redis` Vector Store node.

The keep-alive/ping intervals are set to 60000ms (1 minute) as a robust default, significantly shorter than typical server timeouts, ensuring connections are maintained without excessive background traffic.

**Testing:**

-   Successfully reproduced the "Socket closed unexpectedly" error locally using Queue Mode, SQLite, and a Dockerized Redis instance configured with a short (`--timeout 10`) idle timeout.
-   Verified that applying the keep-alive fixes with a short interval (e.g., 5000ms) prevented the original error under the same test conditions.

**Closes:**

Fixes #2186

### CODE REVIEW

File: packages/components/nodes/cache/RedisCache/RedisCache.ts [hunk 1]
```diff
@@ -126,10 +126,15 @@ const getRedisClient = async (nodeData: INodeData, options: ICommonObject) => {
             host,
             username,
             password,
-            ...tlsOptions
+            ...tlsOptions,
+            keepAlive: 60000,
```
Comment (HenryHengZJ) [inline packages/components/nodes/cache/RedisCache/RedisCache.ts:130]: instead of hardcoding the values, can we have:

`REDIS_KEEP_ALIVE` env variable? `keepAlive: process.env.REDIS_KEEP_ALIVE ?? undefined,`

Comment (nikitas-novatix) [reply packages/components/nodes/cache/RedisCache/RedisCache.ts:130]: Yes, I'll change that now

File: packages/components/nodes/cache/RedisCache/RedisCache.ts [hunk 2]
```diff
@@ -126,10 +126,15 @@ const getRedisClient = async (nodeData: INodeData, options: ICommonObject) => {
...
+            retryStrategy: (times) => Math.min(times * 100, 3000),
         })
     } else {
-        client = new Redis(redisUrl)
+        client = new Redis(redisUrl, {
+            keepAlive: 60000,
+            retryStrategy: (times) => Math.min(times * 100, 3000),
```
[the remark this answers is not in the document]
Comment (nikitas-novatix) [reply packages/components/nodes/cache/RedisCache/RedisCache.ts:136]: No, it was more like an enhancement to add some robustness. I'll remove it for consistency

**Comment by nikitas-novatix** [comment]
@HenryHengZJ thanks for your comments.

I did the following changes:
- Added a REDIS_KEEP_ALIVE env variable, 60000 by default (1min).
- Added a one-liner based on your suggestion, but made it robust to mistakes in the environment variable. So if a person sets something that isn't a number, it still runs (without the KeepAlive mechanism)
- Simplified the code for consistency by removing non-necessary parts (pingInterval, RetryMechanism).

**Review by HenryHengZJ — APPROVED** [review]
