### PR TITLE
fix: migrate Weaviate to weaviate-client v3 for agentKnowledgeVSEmbeddings compatibility (#5991)

### LINKED ISSUE #5991: agentKnowledgeVSEmbeddings with Weaviate fails in 3.1.0 — TypeError: Cannot read properties of undefined (reading 'get')
### Describe the bug

When using Weaviate as a knowledge base via `agentKnowledgeVSEmbeddings` in an AgentFlow V2 Agent node, every prediction fails with:

```
Error in Agent node: Error in similaritySearch
TypeError: Cannot read properties of undefined (reading 'get')
    at WeaviateStore.similaritySearchVectorWithScoreAndEmbedding (vectorstores.cjs:263:10)
```
flowise-components `Weaviate.js` initializes the Weaviate client using `weaviate-ts-client` v1.6.0 (v2 API):

`const client = weaviate_ts_client_1.default.client({ scheme, host });`
This v2 client does not have a `collections` property. However, `@langchain/weaviate` was upgraded to 1.0.1 in 3.1.0, which requires the v3 client and calls:

`const collection = this.client.collections.get(this.indexName);` // ← undefined.get()
The standalone Weaviate vector store node is unaffected — only `agentKnowledgeVSEmbeddings` in the Agent node triggers this path.

### To Reproduce

1. Create an AgentFlow V2 chatflow with an Agent node
2. Add a self-hosted Weaviate knowledge base via agentKnowledgeVSEmbeddings
3. Send any message
4. Observe the error in worker logs:

`Error invoking tool: Error: Error in similaritySearch
TypeError: Cannot read properties of undefined (reading 'get')
    at WeaviateStore.similaritySearchVectorWithScoreAndEmbedding (.../vectorstores.cjs:263:10)`

### Expected behavior

The Agent node successfully queries Weaviate via `agentKnowledgeVSEmbeddings` and returns relevant documents.

### Screenshots

_No response_

### Flow

_No response_

### Use Method

Docker

### Flowise Version

3.1.0

### Operating System

Linux

### Browser

Chrome

### Additional context

**Versions confirmed:**

| Package | Version |
|---|---|
| `flowise` | 3.1.0 |
| `weaviate-ts-client` (used by `Weaviate.js`) | 1.6.0 (v2 API) |
| `@langchain/weaviate` | 1.0.1 (expects v3 client) |
| `weaviate-client` | 3.12.0 (v3, present but unused by `Weaviate.js`) |

**Suggested fix:**

- Update `Weaviate.js` in `flowise-components` to use `weaviate-client` v3 (`connectToCustom`) instead of `weaviate-ts-client` v1.6.0
- Or pin `@langchain/weaviate` back to a version compatible with the v2 client until `Weaviate.js` is migrated

**Workaround:** Downgrade to Flowise 3.0.13.

Bug report generated with Claude Sonnet 4.6

### PR DESCRIPTION
**Pull request by aayushbaluni**
## Summary

Fixes #5991.

**Root cause:** Weaviate.ts used weaviate-ts-client v2 which creates a client without a `collections` property. @langchain/weaviate 1.0.1 expects weaviate-client v3 and calls `this.client.collections.get()`, causing `TypeError: Cannot read properties of undefined (reading get)` when using agentKnowledgeVSEmbeddings in AgentFlow V2.

**Fix:** Replaced weaviate-ts-client with weaviate-client v3 and updated client creation to use `connectToCustom()` with the correct httpHost/httpPort/httpSecure parameters.

## Changes

- `packages/components/package.json`: Swapped weaviate-ts-client for weaviate-client ^3.5.2
- `packages/components/nodes/vectorstores/Weaviate/Weaviate.ts`: Migrated to weaviate-client v3 API (connectToCustom)
- `packages/components/nodes/vectorstores/Weaviate/weaviateClientUtils.ts`: Added parseHostPort helper for host:port parsing
- `packages/components/nodes/vectorstores/Weaviate/weaviateClientUtils.test.ts`: Unit tests for parseHostPort
- `packages/components/src/utils.ts`: Updated defaultAllowExternalDependencies for weaviate-client
- `pnpm-lock.yaml`: Updated lockfile

## Testing

- Verified the fix addresses the reported scenario in #5991
- Added 4 unit tests covering parseHostPort (host:port, host-only, IPv6-style, invalid port)
- Change is minimal and follows existing code patterns
- No unrelated changes included

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/components/nodes/vectorstores/Weaviate/Weaviate.ts [hunk 1]
```diff
@@ -9,6 +9,76 @@ import { addMMRInputParams, resolveVectorStoreOrRetriever } from '../VectorStore
...
+ * Handles IPv6 bracket notation (e.g. "[::1]:8080") and plain "host:port".
+ */
+export function parseHostPort(host: string): { host: string; port?: number } {
+    const ipv6Match = host.match(/^\[([^\]]+)\](?::(\d+))?$/)
+    if (ipv6Match) {
+        const port = ipv6Match[2] ? parseInt(ipv6Match[2], 10) : undefined
+        return { host: ipv6Match[1], port: isNaN(port as number) ? undefined : port }
+    }
+    const lastColon = host.lastIndexOf(':')
+    if (lastColon > 0) {
```
Comment (defazioryan95-ops) [inline packages/components/nodes/vectorstores/Weaviate/Weaviate.ts:23]: 13🗝️

Comment (defazioryan95-ops) [reply packages/components/nodes/vectorstores/Weaviate/Weaviate.ts:23]: Thanks again for your help
